create table if not exists public.report_votes (
  id bigint generated by default as identity primary key,
  option_key text not null unique,
  count bigint not null default 0
);

insert into public.report_votes (option_key, count)
values
  ('up', 0),
  ('down', 0),
  ('poop', 0)
on conflict (option_key) do nothing;

create table if not exists public.report_vote_receipts (
  id bigint generated always as identity primary key,
  visitor_key text not null unique,
  selected_choice text not null check (selected_choice in ('up', 'down', 'poop')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists report_vote_receipts_created_at_idx
  on public.report_vote_receipts (created_at desc);

create or replace function public.cast_report_vote(
  p_choice text,
  p_visitor_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_choice text;
  inserted_receipt boolean := false;
  existing_choice text;
  result_counts jsonb;
begin
  normalized_choice := lower(trim(coalesce(p_choice, '')));

  if normalized_choice not in ('up', 'down', 'poop') then
    raise exception 'invalid_vote_choice';
  end if;

  if trim(coalesce(p_visitor_key, '')) = '' then
    raise exception 'missing_visitor_key';
  end if;

  insert into public.report_vote_receipts (visitor_key, selected_choice)
  values (p_visitor_key, normalized_choice)
  on conflict (visitor_key) do nothing;

  inserted_receipt := found;

  if inserted_receipt then
    update public.report_votes
    set count = count + 1
    where option_key = normalized_choice;
  end if;

  select selected_choice
  into existing_choice
  from public.report_vote_receipts
  where visitor_key = p_visitor_key
  limit 1;

  select jsonb_object_agg(option_key, count)
  into result_counts
  from public.report_votes;

  return jsonb_build_object(
    'applied', inserted_receipt,
    'selected_choice', coalesce(existing_choice, normalized_choice),
    'counts', coalesce(result_counts, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.cast_report_vote(text, text) from public;
revoke all on function public.cast_report_vote(text, text) from anon;
revoke all on function public.cast_report_vote(text, text) from authenticated;
grant execute on function public.cast_report_vote(text, text) to service_role;

alter table public.report_votes enable row level security;
alter table public.report_vote_receipts enable row level security;
alter table public.visit_logs enable row level security;

revoke all on table public.report_votes from public;
revoke all on table public.report_votes from anon;
revoke all on table public.report_votes from authenticated;

revoke all on table public.report_vote_receipts from public;
revoke all on table public.report_vote_receipts from anon;
revoke all on table public.report_vote_receipts from authenticated;

revoke all on table public.visit_logs from public;
revoke all on table public.visit_logs from anon;
revoke all on table public.visit_logs from authenticated;
